apiVersion: v1
kind: PersistentVolume
metadata:
  name: alpha-reports-pv
  namespace: invest-ai
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/alpha-reports
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpha-reports-pvc
  namespace: invest-ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: alpha-reports-pv
  storageClassName: ""
