apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-pvc
  namespace: invest-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
